# Generated by Django 4.2.6 on 2023-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nestdoorapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("addr", models.CharField(max_length=250)),
            ],
        ),
    ]
