# Generated by Django 4.2.6 on 2023-11-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestdoorapp', '0003_rename_user_id_userext_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userext',
            old_name='user',
            new_name='user_id',
        ),
    ]
