# Generated by Django 4.2.6 on 2023-11-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestdoorapp', '0004_rename_user_userext_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
