# Generated by Django 4.2.6 on 2023-11-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestdoorapp', '0005_alter_userext_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userext',
            old_name='user_id',
            new_name='user',
        ),
    ]
