# Generated by Django 4.2.6 on 2023-11-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nestdoorapp', '0002_alter_reply_posted_by'),
        ('nestdoorapp', '0006_rename_user_id_userext_user'),
    ]

    operations = [
    ]
