# Generated by Django 4.2.6 on 2023-11-12 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nestdoorapp', '0007_merge_20231111_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
